# -*- mode: ruby -*-
# vi: set ft=ruby :

required_plugins = %w( vagrant-hostsupdater vagrant-vbguest )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box.
  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking.
  # config.vm.box_check_update = false

  # Create forwarded port mapping to guest from host
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "docker" do |d|
    d.run "robdykedotcom/jnuget-docker",

      # Use the following args to mount /vagrant to /var/lib/jnuget
      # This will include the .xml config files for jnuget
      # args: "-p '8080:8080' -v '/vagrant:/var/lib/jnuget'"

      # Use the following args to mount /vagrant/Packages to /var/lib/jnuget/Packages
      # This will include Packages only
      args: "-p '8080:8080' -v '/vagrant/Packages:/var/lib/jnuget/Packages'"

  end

end
